apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /root/Eks
      name: /root/Eks
  volumes:
  - name: sharan-eks-volume
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-0dd8c9503677761d2
      fsType: ext4
