apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharan-deployment
  labels:
    app: clientapp
  namespace: sharan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientapp
  template:
    metadata:
      labels:
        app: clientapp
    spec:
      containers:
      - name: clientapp
        image: sharanushettar/client
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
          requests:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata: 
  name: clientapp-svc
  namespace: sharan
spec: 
  type: LoadBalancer
  ports:
  - port: 2000
