apiVersion: v1
kind: Pod
metadata: 
    name: non-root-pod
    namespace: sharan
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: alpine
    image: redis:alpine
    
