apiVersion: v1
kind: Pod
metadata:
  name: nginx
replicas: 2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: apache
    image: nginx:1.14.2
    ports:
    - containerPort: 80
