apiVersion: v1
kind: Pod
metadata:
  name: super-user
  labels:
    name: super-user-pod
  namespace: sharan
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: busybox:1.28
    securityContext:
     capabilities:
        add: ["SYS_TIME"]
    name: super-user-pod
