kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sharan
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "amazonEBS"
  storageClassName: gp2
